name: Crawl GitHub Pages
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      OUTPUT: endpoints.json
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run crawler
        run: |
          USERNAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          python .github/scripts/crawler.py "https://${USERNAME}.github.io/" "${USERNAME}"
      - name: Upload endpoints.json artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pages
          path: ${OUTPUT}

      - name: Commit and Push
        run: |
          USERNAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${USERNAME}/${USERNAME}.github.io.git
          mv ${OUTPUT} ./docs/${OUTPUT}
          git add ./docs/${OUTPUT}
          git commit -am "update page endpoints"
          git push
